### ISSUE TITLE
Uninitialized Constant SolidusSeo::Jsonld::Base

### ISSUE THREAD

**Issue by s3749653** [karmakatahdin/solidus_seo#11]
As per the previously raised issue, the same thing is occurring for myself. The application works fine locally, but as soon as it is deployed the following error comes up.

ActionView::Template::Error (uninitialized constant SolidusSeo::Jsonld::Base Did you mean? Base64)

solidus v2.10
Rails 6.0.3.2

Any help would be appreciated
Thank you!

**Comment by jontarg** [comment]
Hello! Which version of solidus_seo are you using?
