### ISSUE TITLE
Uninitialized Constant SolidusSeo::Jsonld::Base

### ISSUE THREAD

**Issue by octoxan** [karmakatahdin/solidus_seo#6]
Just added this gem, installed and tested it locally just fine. The json shows up in the source.

Went to deploy and every page on the site is now a 500 error:

`ActionView::Template::Error (uninitialized constant SolidusSeo::Jsonld::Base
Did you mean?  Base64)`

**Comment by octoxan** [comment]
Setting `config.cache_classes = false` in the production.rb fixes the issue, but that's not ideal.

**Comment by octoxan** [comment]
Tried on 3 different servers and it seems cache_classes being true always breaks solidus_seo. Not sure where to look next =(

**Comment by dportalesr** [comment]
@octoxan Hi! Interesting. Which version of Rails/Solidus are you using?

**Comment by octoxan** [comment]
Rails 5.2.3
Solidus 2.9.2

Yeah it seems no matter what I do, with this gem and class caching on, the site says SolidusSeo::Jsonld::Base is an undefined constant on every page.

What can I provide to help?

**Comment by jontarg** [comment]
Thanks for your report! This should be fixed now. Let us know if something else comes up!

**Comment by dportalesr** [comment]
Thanks for your report! This should be fixed now. Let us know if something else comes up!
